@host=http://localhost:3000

###
GET {{host}}/categories?category_type=INGRESO&name=cat

###
GET {{host}}/categories/dc03a51f-548c-4fbb-a408-66ad700c3cb3

###
POST {{host}}/categories
Content-Type: application/json

{
  "name": "categoria 1",
  "category_type": "INGRESO",
  "note": "-"
}

###
PUT  {{host}}/categories/dc03a51f-548c-4fbb-a408-66ad700c3cb3
Content-Type: application/json

{
  "name": "categoria 4",
  "category_type": "INGRESO",
  "note": "-"
}

###
DELETE {{host}}/categories/efe8e69a-1b5f-441a-832f-39d23e8efd69
